### ISSUE TITLE
Several questions about NinevehGL possibility

### ISSUE THREAD

**Issue by unco182** [NinevehGL/NinevehGL#10]
Hi, 

I'm trying to find a framework/SDK to be able to do the following task and I'm wondering if I can do that easily with Nineveh :
- Importing an IFC file with its annotations
- Rendering the model and being able to move in it 
- Being able to read and write new annotations on my model 
- Exporting the model and its annotations in IFC format.

Thanks in advance for your answers !

**Comment by dineybomfim** [comment]
Hello,

Right now, NinvehGL doesn't support IFC files.
It only support .dae, .obj and .ngl
However its structure was made to support "N" kinds of file parsers, so creating a parser for IFC is just a matter of following the protocols for file parser.

We'll be glad in receiving such enhancement, if you do it, please send us a pull request.

**Comment by unco182** [comment]
Thanks for your answer, I'll sure do if I finally choose NinevhsGL as a solution for my 3D modelisation :)
